CREATE DATABASE FlightDatabase;
USE FlightDatabase;

CREATE TABLE Airlines (
    Airline_ID INT AUTO_INCREMENT PRIMARY KEY,
    IATA_CODE VARCHAR(3) UNIQUE,
    AIRLINE VARCHAR(255)
);

CREATE TABLE Airports (
    Airport_ID INT AUTO_INCREMENT PRIMARY KEY,
    IATA_CODE VARCHAR(3) UNIQUE,
    AIRPORT VARCHAR(255),
    CITY VARCHAR(255),
    STATE VARCHAR(255),
    COUNTRY VARCHAR(255),
    LATITUDE DOUBLE,
    LONGITUDE DOUBLE
);

CREATE TABLE Flights (
    Flight_ID INT AUTO_INCREMENT PRIMARY KEY,
    YEAR INT,
    MONTH INT,
    DAY INT,
    DAY_OF_WEEK INT,
    AIRLINE VARCHAR(5),
    FLIGHT_NUMBER INT,
    TAIL_NUMBER VARCHAR(10),
    ORIGIN_AIRPORT VARCHAR(5),
    DESTINATION_AIRPORT VARCHAR(5),
    SCHEDULED_DEPARTURE INT,
    DEPARTURE_TIME DOUBLE,
    DEPARTURE_DELAY DOUBLE,
    TAXI_OUT DOUBLE,
    WHEELS_OFF DOUBLE,
    SCHEDULED_TIME DOUBLE,
    ELAPSED_TIME DOUBLE,
    AIR_TIME DOUBLE,
    DISTANCE INT,
    WHEELS_ON DOUBLE,
    TAXI_IN DOUBLE,
    SCHEDULED_ARRIVAL INT,
    ARRIVAL_TIME DOUBLE,
    ARRIVAL_DELAY DOUBLE,
    DIVERTED INT,
    CANCELLED INT,
    AIR_SYSTEM_DELAY DOUBLE,
    SECURITY_DELAY DOUBLE,
    AIRLINE_DELAY DOUBLE,
    LATE_AIRCRAFT_DELAY DOUBLE,
    WEATHER_DELAY DOUBLE
);